$ErrorActionPreference = "Stop"
Write-Host "Starting VERIFICERT with real local blockchain transactions"
Write-Host "1. npm install"
Write-Host "2. docker compose -f infrastructure/docker-compose.yml up -d"
Write-Host "3. npm run blockchain"
Write-Host "4. npm run deploy:local"
Write-Host "5. Copy VERIFICERT_CONTRACT_ADDRESS and the issuer private key into .env"
Write-Host "6. cd apps/api; python -m app.db.seed; python -m uvicorn app.main:app --reload --port 8000"
Write-Host "7. npm run web"
